name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Rename JAR file
        run: |
          JAR_NAME="build/libs/LabsJava4sem-0.0.1-SNAPSHOT.jar"
          NEW_JAR_NAME="distanceApplication-0.0.1-SNAPSHOT.jar"
          mv $JAR_NAME build/libs/$NEW_JAR_NAME
          echo "Renamed $JAR_NAME to $NEW_JAR_NAME"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: build/libs/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 20
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          
      - name: Install Railway
        run: npm i -g @railway/cli
        
      - name: Deploy
        run: railway up --service 5a6a191d-e3f4-48ac-b69f-4388277b2086
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

  release-project:
    name: "Release project"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-app
      - name: Test artifact download
        run: ls -R
